Webserver/Controllers/FacultiesController.cs
using ASPNET_MVC_Samples.Models;
using Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webserver.Data.Repositories;

namespace Webserver.Controllers
{
    public class FacultiesController : Controller
    {
        private readonly IFacultyRepository _facultyRepository;
        private readonly IUniversityRepository _universityRepository;
        private readonly IReviewRepository _reviewRepository;

        public FacultiesController(IFacultyRepository facultyRepository, IUniversityRepository universityRepository, IReviewRepository reviewRepository)
        {
            _facultyRepository = facultyRepository;
            _universityRepository = universityRepository;
            _reviewRepository = reviewRepository;
        }

        // GET: Faculties/{universityId}
        public ActionResult Index(int universityId)
        {
            University university = _universityRepository.GetById(universityId);
            if (university == null)
            {
                return HttpNotFound();
            }

            ViewBag.UniversityName = university.Name;
            ViewBag.UniversityId = universityId;

            IEnumerable<Faculty> faculties = _facultyRepository.GetMany(faculty => faculty.UniversityId == universityId);
            return View(faculties);
        }

        // GET: Faculties/Details/{id}
        public ActionResult Details(int id)
        {
            Faculty faculty = _facultyRepository.GetById(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            var reviewList = _reviewRepository.GetMany(review => review.FacultyId.Equals(id));

            List<DataPoint> dataPoints = new List<DataPoint>{
                new DataPoint(1, reviewList.Where(review => review.Value.Equals(1)).Count()),
                new DataPoint(2, reviewList.Where(review => review.Value.Equals(2)).Count()),
                new DataPoint(3, reviewList.Where(review => review.Value.Equals(3)).Count()),
                new DataPoint(4, reviewList.Where(review => review.Value.Equals(4)).Count()),
                new DataPoint(5, reviewList.Where(review => review.Value.Equals(5)).Count()),
            };

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);

            return View(faculty);
        }

        // GET: Faculties/Edit/{id}
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            Faculty faculty = _facultyRepository.GetById(id);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            return View(faculty);
        }

        // POST: Faculties/Edit/{id}
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id, Name")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                Faculty facultyToBeUpdated = _facultyRepository.GetById(faculty.Id);
                facultyToBeUpdated.Name = faculty.Name;

                _facultyRepository.GetEntry(facultyToBeUpdated).State = EntityState.Modified;
                await _facultyRepository.Commit();

                RedirectToAction("Details", new { id = faculty.Id });
            }

            return View(faculty);
        }

        // GET: Faculties/Add/{universityId}
        [Authorize(Roles = "Administrator")]
        public ActionResult Add(int universityId)
        {
            ViewBag.UniversityId = universityId;
            return View();
        }

        // POST: Faculties/Add
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add([Bind(Include = "UniversityId, Name")] Faculty faculty)
        {
            if (ModelState.IsValid)
            {
                _facultyRepository.Add(faculty);
                await _facultyRepository.Commit();
                return RedirectToAction("Index", new { universityId = faculty.UniversityId });
            }

            return View(faculty);
        }
    }
}

Webserver/Controllers/ProgrammesController.cs
using ASPNET_MVC_Samples.Models;
using Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webserver.Data.Repositories;

namespace Webserver.Controllers
{
    public class ProgrammesController : Controller
    {
        private readonly IProgrammeRepository _programmeRepository;
        private readonly IFacultyRepository _facultyRepository;
        private readonly IReviewRepository _reviewRepository;

        public ProgrammesController(IProgrammeRepository programmeRepository, IFacultyRepository facultyRepository, IReviewRepository reviewRepository)
        {
            _programmeRepository = programmeRepository;
            _facultyRepository = facultyRepository;
            _reviewRepository = reviewRepository;
        }

        // GET: Programmes/{facultyId}
        public ActionResult Index(int facultyId)
        {
            Faculty faculty = _facultyRepository.GetById(facultyId);
            if (faculty == null)
            {
                return HttpNotFound();
            }

            ViewBag.FacultyName = faculty.Name;
            ViewBag.FacultyId = facultyId;

            IEnumerable<Programme> programmes = _programmeRepository.GetMany(programme => programme.FacultyId == facultyId);
            return View(programmes);
        }

        // GET: Programmes/Details/{id}
        public ActionResult Details(int id)
        {
            Programme programme = _programmeRepository.GetById(id);
            if (programme == null)
            {
                return HttpNotFound();
            }

            var reviewList = _reviewRepository.GetMany(review => review.ProgrammeId.Equals(id));

            List<DataPoint> dataPoints = new List<DataPoint>{
                new DataPoint(1, reviewList.Where(review => review.Value.Equals(1)).Count()),
                new DataPoint(2, reviewList.Where(review => review.Value.Equals(2)).Count()),
                new DataPoint(3, reviewList.Where(review => review.Value.Equals(3)).Count()),
                new DataPoint(4, reviewList.Where(review => review.Value.Equals(4)).Count()),
                new DataPoint(5, reviewList.Where(review => review.Value.Equals(5)).Count()),
            };

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);

            return View(programme);
        }

        // GET: Programmes/Edit/{id}
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            Programme programme = _programmeRepository.GetById(id);
            if (programme == null)
            {
                return HttpNotFound();
            }

            return View(programme);
        }

        // POST: Programmes/Edit/{id}
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id, Name")] Programme programme)
        {
            if (ModelState.IsValid)
            {
                Programme programmeToBeUpdated = _programmeRepository.GetById(programme.Id);
                programmeToBeUpdated.Name = programme.Name;

                _programmeRepository.GetEntry(programmeToBeUpdated).State = EntityState.Modified;
                await _programmeRepository.Commit();

                RedirectToAction("Details", new { id = programme.Id });
            }

            return View(programme);
        }

        // GET: Programmes/Add/{facultyId}
        [Authorize(Roles = "Administrator")]
        public ActionResult Add(int facultyId)
        {
            ViewBag.FacultyId = facultyId;
            return View();
        }

        // POST: Programmes/Add
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add([Bind(Include = "FacultyId, Name")] Programme programme)
        {
            if (ModelState.IsValid)
            {
                _programmeRepository.Add(programme);
                await _programmeRepository.Commit();
                return RedirectToAction("Index", new { facultyId = programme.FacultyId });
            }

            return View(programme);
        }
    }
}

Webserver/Controllers/UniversitiesController.cs
using ASPNET_MVC_Samples.Models;
using Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webserver.Data.Repositories;
using Webserver.Enums;
using Webserver.Services;
using Webserver.Services.Api;

namespace Webserver.Controllers
{
    public class UniversitiesController : Controller
    {
        private readonly IUniversityRepository _universityRepository;
        private readonly IReviewRepository _reviewRepository;
        private readonly IMapsApi _mapsApi;
        private readonly IPaginationHandler<University, UniversitySortOrder> _paginationHandler;

        public UniversitiesController
        (
            IUniversityRepository universityRepository,
            IReviewRepository reviewRepository,
            IMapsApi mapsApi,
            IPaginationHandler<University, UniversitySortOrder> paginationHandler
        )
        {
            _universityRepository = universityRepository;
            _reviewRepository = reviewRepository;
            _mapsApi = mapsApi;
            _paginationHandler = paginationHandler;
        }

        // GET: Universities/{page}/{searchCriteria}/{sortOrder}/{country}
        public ActionResult Index(int? page, string searchCriteria = null, UniversitySortOrder sortOrder = UniversitySortOrder.NAME_ASC, string country = null)
        {
            IEnumerable<University> universities;

            Session["CurrentUniversityPage"] = page;
            Session["UniversitySortOrder"] = sortOrder;
            Session["UniversitySearchCriteria"] = searchCriteria;
            Session["UniversityCountry"] = country;

            ViewBag.SearchCriteria = searchCriteria;
            ViewBag.Country = country;

            // Default value from html dropdown list
            if (country == "")
            {
                country = null;
            }

            if (country != null && searchCriteria != null)
            {
                universities = _universityRepository.GetMany(university => university.Country == country && university.Name.Contains(searchCriteria));
            }
            else if (searchCriteria != null)
            {
                universities = _universityRepository.GetMany(university => university.Name.Contains(searchCriteria));
            }
            else if (country != null)
            {
                universities = _universityRepository.GetMany(university => university.Country == country);
            }
            else
            {
                universities = _universityRepository.GetAll();
            }

            return View(_paginationHandler.ConstructViewModel(universities, page, sortOrder));
        }

        // GET: Universities/RedirectToIndex
        public ActionResult RedirectToIndex()
        {
            string searchCriteriaInSessionData = Session["UniversitySearchCriteria"]?.ToString();
            string countryInSessionData = Session["UniversityCountry"]?.ToString();
            int? currentPageInSessionData = (int?)Session["CurrentUniversityPage"];

            UniversitySortOrder sortOrderInSessionData =
                Session["UniversitySortOrder"] != null
                ? (UniversitySortOrder)Session["UniversitySortOrder"]
                : UniversitySortOrder.NAME_ASC;

            return RedirectToAction("Index",
                new
                {
                    page = currentPageInSessionData,
                    searchCriteria = searchCriteriaInSessionData,
                    sortOrder = sortOrderInSessionData,
                    country = countryInSessionData
                });
        }

        // GET: Universities/Details/{id}

        public ActionResult Details(int id)
        {
            University university = _universityRepository.GetById(id);
            if (university == null)
            {
                return HttpNotFound();
            }

            ViewBag.UniversityId = id;
            var reviewList = _reviewRepository.GetMany(review => review.UniversityId.Equals(id));

            List<DataPoint> dataPoints = new List<DataPoint>{
                new DataPoint(1, reviewList.Where(review => review.Value.Equals(1)).Count()),
                new DataPoint(2, reviewList.Where(review => review.Value.Equals(2)).Count()),
                new DataPoint(3, reviewList.Where(review => review.Value.Equals(3)).Count()),
                new DataPoint(4, reviewList.Where(review => review.Value.Equals(4)).Count()),
                new DataPoint(5, reviewList.Where(review => review.Value.Equals(5)).Count()),
            };

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
            ViewBag.GoogleMapUri = _mapsApi.GetStaticMapUri(university.Name);

            return View(university);
        }

        // GET: Universities/Edit/{id}
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            University university = _universityRepository.GetById(id);
            if (university == null)
            {
                return HttpNotFound();
            }

            return View(university);
        }

        // POST: Universities/Edit/{id}
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id, Name, Description")] University university)
        {
            if (ModelState.IsValid)
            {
                University universityToBeUpdated = _universityRepository.GetById(university.Id);
                universityToBeUpdated.Name = university.Name;
                universityToBeUpdated.Description = university.Description;

                _universityRepository.GetEntry(universityToBeUpdated).State = EntityState.Modified;
                await _universityRepository.Commit();

                RedirectToAction("Details", new { id = university.Id });
            }

            return View(university);
        }

        // GET: Universities/Add
        [Authorize(Roles = "Administrator")]
        public ActionResult Add()
        {
            return View();
        }

        // POST: Universities/Add
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add([Bind(Include = "Name, Description")] University university)
        {
            if (ModelState.IsValid)
            {
                _universityRepository.Add(university);
                await _universityRepository.Commit();
                return RedirectToAction("Index");
            }

            return View(university);
        }
    }
}

Webserver/Controllers/UniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webserver.Controllers
{
    public class UniversityController : Controller
    {
        // GET: University
        public ActionResult University()
        {

            ViewBag.Message = "This is the university profile";

            return View();
        
        }
    }
}

Webserver/Views/Reviews/Delete.cshtml
@model Models.Review

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UniversityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniversityId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacultyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacultyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgrammeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgrammeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
    </dl>

    @using (Html.BeginForm("Delete", "Reviews", new { id = Model.Id }, FormMethod.Post))
    {
    @Html.AntiForgeryToken()

    <div class="form-actions no-color">
        <input type="submit" value="Delete" class="btn btn-default" />
        @if (Model.UniversityId != 0)
            {
        <p>
            @Html.ActionLink("Back to List", "RedirectToUniversity", new { id = Model.UniversityId })
        </p>
            }
            else if (Model.FacultyId != 0)
            {
        <p>
            @Html.ActionLink("Back to List", "RedirectToFaculty", new { id = Model.FacultyId })
        </p>
            }
            else if (Model.ProgrammeId != 0)
            {
        <p>
            @Html.ActionLink("Back to List", "RedirectToProgramme", new { id = Model.ProgrammeId })
        </p>
            }
    </div>
    }
</div>

Webserver/Views/Reviews/Details.cshtml
@model Models.Review

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Review</h4>
    <hr />
    <dl class="dl-horizontal">

        @if (Request.IsAuthenticated)
        {
            if (User.IsInRole("Administrator"))
            {
        <dt>
            @Html.DisplayNameFor(model => model.UniversityId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UniversityId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FacultyId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FacultyId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProgrammeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProgrammeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserId)
        </dd>
            }
        }

        <dt>
            @Html.DisplayNameFor(model => model.Text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Value)
        </dd>
    </dl>
</div>

@if (Model.UniversityId != 0)
{
<p>
    @Html.ActionLink("Back to List", "RedirectToUniversity", new { id = Model.UniversityId })
</p>
}
else if (Model.FacultyId != 0)
{
<p>
    @Html.ActionLink("Back to List", "RedirectToFaculty", new { id = Model.FacultyId })
</p>
}
else if (Model.ProgrammeId != 0)
{
<p>
    @Html.ActionLink("Back to List", "RedirectToProgramme", new { id = Model.ProgrammeId })
</p>
}

@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Administrator"))
    {
<p>
    @Html.ActionLink("Delete", "Delete", new { id = Model.Id })
</p>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
</p>
    }
}

Webserver/Views/Reviews/Edit.cshtml
@model Models.Review

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Review</h4>
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Text, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Text, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Text, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

@if (Model.UniversityId != 0)
{
<p>
    @Html.ActionLink("Back to List", "RedirectToUniversity", new { id = Model.UniversityId })
</p>
}
else if (Model.FacultyId != 0)
{
<p>
    @Html.ActionLink("Back to List", "RedirectToFaculty", new { id = Model.FacultyId })
</p>
}
else if (Model.ProgrammeId != 0)
{
<p>
    @Html.ActionLink("Back to List", "RedirectToProgramme", new { id = Model.ProgrammeId })
</p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webserver/Views/Reviews/Faculty.cshtml
@model Webserver.Models.ViewModels.Pagination.PagerViewModel<Models.Review, Webserver.Enums.ReviewSortOrder>

@{
    ViewBag.Title = "Index";
}

<h2>Community Reviews</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Items.LastOrDefault().Text)
        </th>
        <th>
            @if (Model.SortOrder == Webserver.Enums.ReviewSortOrder.VALUE_ASC)
            {
            @Html.ActionLink("Value", "Faculty",
                    new { id = ViewBag.FacultyId, page = Model.Pager.CurrentPage, sortOrder = Webserver.Enums.ReviewSortOrder.VALUE_DESC })
            }
            else
            {
            @Html.ActionLink("Value", "Faculty",
                    new { id = ViewBag.FacultyId, page = Model.Pager.CurrentPage, sortOrder = Webserver.Enums.ReviewSortOrder.VALUE_ASC })
            }
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Items)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
    </tr>
    }
</table>

@if (Model.Pager.EndPage > 1)
{
<ul class="pagination">
    @if (Model.Pager.CurrentPage > 1)
        {
    <li>
        @Html.ActionLink("First", "Faculty", new { id = ViewBag.FacultyId, sortOrder = Model.SortOrder })
    </li>
    <li>
        @Html.ActionLink("Previous", "Faculty", new { id = ViewBag.FacultyId, page = Model.Pager.CurrentPage - 1, sortOrder = Model.SortOrder })
    </li>
        }

    @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
        {
    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
        @Html.ActionLink(page.ToString(), "Faculty", new { id = ViewBag.FacultyId, page = page, sortOrder = Model.SortOrder })
    </li>
        }

    @if (Model.Pager.CurrentPage < Model.Pager.TotalPageCount)
        {
    <li>
        @Html.ActionLink("Next", "Faculty", new { id = ViewBag.FacultyId, page = Model.Pager.CurrentPage + 1, sortOrder = Model.SortOrder })
    </li>
    <li>
        @Html.ActionLink("Last", "Faculty", new { id = ViewBag.FacultyId, page = Model.Pager.TotalPageCount, sortOrder = Model.SortOrder })
    </li>
        }
</ul>
}

<p>
    @Html.ActionLink("Back To Faculty Details", "Details", "Faculties", new { id = ViewBag.FacultyId }, null)
</p>

Webserver/Views/Reviews/Index.cshtml
@model IEnumerable<Webserver.Models.Review>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Community Reviews</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UserId)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UserId)
        </td>
    </tr>
}

</table>

<p>
    @Html.ActionLink("Back To Universities", "Index", "Universities")
</p>

Webserver/Views/Reviews/Programme.cshtml
@model Webserver.Models.ViewModels.Pagination.PagerViewModel<Models.Review, Webserver.Enums.ReviewSortOrder>

@{
    ViewBag.Title = "Index";
}

<h2>Community Reviews</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Items.LastOrDefault().Text)
        </th>
        <th>
            @if (Model.SortOrder == Webserver.Enums.ReviewSortOrder.VALUE_ASC)
            {
            @Html.ActionLink("Value", "Programme",
                    new { id = ViewBag.ProgrammeId, page = Model.Pager.CurrentPage, sortOrder = Webserver.Enums.ReviewSortOrder.VALUE_DESC })
            }
            else
            {
            @Html.ActionLink("Value", "Programme",
                    new { id = ViewBag.ProgrammeId, page = Model.Pager.CurrentPage, sortOrder = Webserver.Enums.ReviewSortOrder.VALUE_ASC })
            }
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Items)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
    </tr>
    }
</table>

@if (Model.Pager.EndPage > 1)
{
<ul class="pagination">
    @if (Model.Pager.CurrentPage > 1)
        {
    <li>
        @Html.ActionLink("First", "Programme", new { id = ViewBag.ProgrammeId, sortOrder = Model.SortOrder })
    </li>
    <li>
        @Html.ActionLink("Previous", "Programme", new { id = ViewBag.ProgrammeId, page = Model.Pager.CurrentPage - 1, sortOrder = Model.SortOrder })
    </li>
        }

    @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
        {
    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
        @Html.ActionLink(page.ToString(), "Programme", new { id = ViewBag.ProgrammeId, page = page, sortOrder = Model.SortOrder })
    </li>
        }

    @if (Model.Pager.CurrentPage < Model.Pager.TotalPageCount)
        {
    <li>
        @Html.ActionLink("Next", "Programme", new { id = ViewBag.ProgrammeId, page = Model.Pager.CurrentPage + 1, sortOrder = Model.SortOrder })
    </li>
    <li>
        @Html.ActionLink("Last", "Programme", new { id = ViewBag.ProgrammeId, page = Model.Pager.TotalPageCount, sortOrder = Model.SortOrder })
    </li>
        }
</ul>
}

<p>
    @Html.ActionLink("Back To Programme Details", "Details", "Programmes", new { id = ViewBag.ProgrammeId }, null)
</p>

Webserver/Views/Reviews/University.cshtml
@model Webserver.Models.ViewModels.Pagination.PagerViewModel<Models.Review, Webserver.Enums.ReviewSortOrder>

@{
    ViewBag.Title = "Index";
}

<h2>Community Reviews</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Items.LastOrDefault().Text)
        </th>
        <th>
            @if (Model.SortOrder == Webserver.Enums.ReviewSortOrder.VALUE_ASC)
            {
            @Html.ActionLink("Value", "University",
                    new { id = ViewBag.UniversityId, page = Model.Pager.CurrentPage, sortOrder = Webserver.Enums.ReviewSortOrder.VALUE_DESC })
            }
            else
            {
            @Html.ActionLink("Value", "University",
                    new { id = ViewBag.UniversityId, page = Model.Pager.CurrentPage, sortOrder = Webserver.Enums.ReviewSortOrder.VALUE_ASC })
            }
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Items)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Value)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id = item.Id })
        </td>
    </tr>
    }
</table>

@if (Model.Pager.EndPage > 1)
{
<ul class="pagination">
    @if (Model.Pager.CurrentPage > 1)
        {
    <li>
        @Html.ActionLink("First", "University", new { id = ViewBag.UniversityId, sortOrder = Model.SortOrder })
    </li>
    <li>
        @Html.ActionLink("Previous", "University", new { id = ViewBag.UniversityId, page = Model.Pager.CurrentPage - 1, sortOrder = Model.SortOrder })
    </li>
        }

    @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
        {
    <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
        @Html.ActionLink(page.ToString(), "University", new { id = ViewBag.UniversityId, page = page, sortOrder = Model.SortOrder })
    </li>
        }

    @if (Model.Pager.CurrentPage < Model.Pager.TotalPageCount)
        {
    <li>
        @Html.ActionLink("Next", "University", new { id = ViewBag.UniversityId, page = Model.Pager.CurrentPage + 1, sortOrder = Model.SortOrder })
    </li>
    <li>
        @Html.ActionLink("Last", "University", new { id = ViewBag.UniversityId, page = Model.Pager.TotalPageCount, sortOrder = Model.SortOrder })
    </li>
        }
</ul>
}

<p>
    @Html.ActionLink("Back To University Details", "Details", "Universities", new { id = ViewBag.UniversityId }, null)
</p>