Webserver/Controllers/AddReviewController.cs
using Microsoft.AspNet.Identity;
using Models;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webserver.Data.Repositories;

namespace Webserver.Controllers
{
    [Authorize]
    public class AddReviewController : Controller
    {
        private readonly IReviewRepository _reviewRepository;

        public AddReviewController(IReviewRepository reviewRepository)
        {
            _reviewRepository = reviewRepository;
        }

        // GET: AddReview
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UniversityReview(int universityId)
        {
            ViewBag.universityId = universityId;
            return View();
        }

        public ActionResult FacultyReview(int facultyId)
        {
            ViewBag.facultyId = facultyId;
            return View();
        }

        public ActionResult ProgrammeReview(int programmeId)
        {
            ViewBag.programmeId = programmeId;
            return View();
        }

        [HttpPost]
        public ActionResult ReviewUniversity(Review model, int id)
        {
            model.UniversityId = id;
            if (model.Value > 5 || model.Value < 1)
            {
                model.Value = 5;
            }

            model.UserId = User.Identity.GetUserId();
            _reviewRepository.Add(model);
            Task task = Task.Run(async () => await _reviewRepository.Commit());
            task.Wait();
            return RedirectToAction("Details", "Universities", new { id = id });
        }

        [HttpPost]
        public ActionResult ReviewFaculty(Review model, int id)
        {
            model.FacultyId = id;
            if (model.Value > 5 || model.Value < 1)
            {
                model.Value = 5;
            }

            model.UserId = User.Identity.GetUserId();
            _reviewRepository.Add(model);
            Task task = Task.Run(async () => await _reviewRepository.Commit());
            task.Wait();
            return RedirectToAction("Details", "Faculties", new { id = id });
        }

        [HttpPost]
        public ActionResult ReviewProgramme(Review model, int id)
        {
            model.ProgrammeId = id;
            if (model.Value > 5 || model.Value < 1)
            {
                model.Value = 5;
            }

            model.UserId = User.Identity.GetUserId();
            _reviewRepository.Add(model);
            Task task = Task.Run(async () => await _reviewRepository.Commit());
            task.Wait();
            return RedirectToAction("Details", "Programmes", new { id = id });
        }
    }
}

Webserver/Controllers/UniversitiesController.cs
using ASPNET_MVC_Samples.Models;
using Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webserver.Data.Repositories;
using Webserver.Enums;
using Webserver.Services;
using Webserver.Services.Api;

namespace Webserver.Controllers
{
    public class UniversitiesController : Controller
    {
        private readonly IUniversityRepository _universityRepository;
        private readonly IReviewRepository _reviewRepository;
        private readonly IMapsApi _mapsApi;
        private readonly IPaginationHandler<University, UniversitySortOrder> _paginationHandler;

        public UniversitiesController
        (
            IUniversityRepository universityRepository,
            IReviewRepository reviewRepository,
            IMapsApi mapsApi,
            IPaginationHandler<University, UniversitySortOrder> paginationHandler
        )
        {
            _universityRepository = universityRepository;
            _reviewRepository = reviewRepository;
            _mapsApi = mapsApi;
            _paginationHandler = paginationHandler;
        }

        // GET: Universities/{page}/{searchCriteria}/{sortOrder}/{country}
        public ActionResult Index(int? page, string searchCriteria = null, UniversitySortOrder sortOrder = UniversitySortOrder.NAME_ASC, string country = null)
        {
            IEnumerable<University> universities;

            Session["CurrentUniversityPage"] = page;
            Session["UniversitySortOrder"] = sortOrder;
            Session["UniversitySearchCriteria"] = searchCriteria;
            Session["UniversityCountry"] = country;

            ViewBag.SearchCriteria = searchCriteria;
            ViewBag.Country = country;

            // Default value from html dropdown list
            if (country == "")
            {
                country = null;
            }

            if (country != null && searchCriteria != null)
            {
                universities = _universityRepository.GetMany(university => university.Country == country && university.Name.Contains(searchCriteria));
            }
            else if (searchCriteria != null)
            {
                universities = _universityRepository.GetMany(university => university.Name.Contains(searchCriteria));
            }
            else if (country != null)
            {
                universities = _universityRepository.GetMany(university => university.Country == country);
            }
            else
            {
                universities = _universityRepository.GetAll();
            }

            return View(_paginationHandler.ConstructViewModel(universities, page, sortOrder));
        }

        // GET: Universities/RedirectToIndex
        public ActionResult RedirectToIndex()
        {
            string searchCriteriaInSessionData = Session["UniversitySearchCriteria"]?.ToString();
            string countryInSessionData = Session["UniversityCountry"]?.ToString();
            int? currentPageInSessionData = (int?)Session["CurrentUniversityPage"];

            UniversitySortOrder sortOrderInSessionData =
                Session["UniversitySortOrder"] != null
                ? (UniversitySortOrder)Session["UniversitySortOrder"]
                : UniversitySortOrder.NAME_ASC;

            return RedirectToAction("Index",
                new
                {
                    page = currentPageInSessionData,
                    searchCriteria = searchCriteriaInSessionData,
                    sortOrder = sortOrderInSessionData,
                    country = countryInSessionData
                });
        }

        // GET: Universities/Details/{id}

        public ActionResult Details(int id)
        {
            University university = _universityRepository.GetById(id);
            if (university == null)
            {
                return HttpNotFound();
            }

            ViewBag.UniversityId = id;
            var reviewList = _reviewRepository.GetMany(review => review.UniversityId.Equals(id));

            List<DataPoint> dataPoints = new List<DataPoint>{
                new DataPoint(1, reviewList.Where(review => review.Value.Equals(1)).Count()),
                new DataPoint(2, reviewList.Where(review => review.Value.Equals(2)).Count()),
                new DataPoint(3, reviewList.Where(review => review.Value.Equals(3)).Count()),
                new DataPoint(4, reviewList.Where(review => review.Value.Equals(4)).Count()),
                new DataPoint(5, reviewList.Where(review => review.Value.Equals(5)).Count()),
            };

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
            ViewBag.GoogleMapUri = _mapsApi.GetStaticMapUri(university.Name);

            return View(university);
        }

        // GET: Universities/Edit/{id}
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            University university = _universityRepository.GetById(id);
            if (university == null)
            {
                return HttpNotFound();
            }

            return View(university);
        }

        // POST: Universities/Edit/{id}
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id, Name, Description")] University university)
        {
            if (ModelState.IsValid)
            {
                University universityToBeUpdated = _universityRepository.GetById(university.Id);
                universityToBeUpdated.Name = university.Name;
                universityToBeUpdated.Description = university.Description;

                _universityRepository.GetEntry(universityToBeUpdated).State = EntityState.Modified;
                await _universityRepository.Commit();

                RedirectToAction("Details", new { id = university.Id });
            }

            return View(university);
        }

        // GET: Universities/Add
        [Authorize(Roles = "Administrator")]
        public ActionResult Add()
        {
            return View();
        }

        // POST: Universities/Add
        [HttpPost]
        [Authorize(Roles = "Administrator")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add([Bind(Include = "Name, Description")] University university)
        {
            if (ModelState.IsValid)
            {
                _universityRepository.Add(university);
                await _universityRepository.Commit();
                return RedirectToAction("Index");
            }

            return View(university);
        }
    }
}

Webserver/Controllers/UniversityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Webserver.Controllers
{
    public class UniversityController : Controller
    {
        // GET: University
        public ActionResult University()
        {

            ViewBag.Message = "This is the university profile";

            return View();
        
        }
    }
}

Webserver/Views/Universities/Add.cshtml
@model Models.University

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "RedirectToIndex")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webserver/Views/Universities/Details.cshtml
@model Models.University

@{
    ViewBag.Title = "Details";
}

<h2>@Html.DisplayFor(model => model.Name)</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        @if (!String.IsNullOrEmpty(Model.Website))
        {
            <dt>
                @Html.DisplayNameFor(model => model.Website)
            </dt>

            <dd>
                <a href='@string.Format("{0}", Model.Website)'>Click to visit</a>
            </dd>
        }
    </dl>
</div>

<p>
    @Html.ActionLink("Back to List", "RedirectToIndex")
</p>
<p>
    @Html.ActionLink("See Faculties", "Index", "Faculties", new { universityId = Model.Id }, null)
</p>
<p>
    @Html.ActionLink("Check Reviews", "University", "Reviews", new { id = Model.Id }, null)
</p>
<p>
    @Html.ActionLink("Add a review", "UniversityReview", "AddReview", new { universityId = Model.Id }, null)
</p>

@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Administrator"))
    {
        <p>
            @Html.ActionLink("Edit", "Edit", new { id = Model.Id })
        </p>
    }
}
<script src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.min.js"></script>

<div id="chartContainer" style="height:300px; width: 100%;"></div>

<script type="text/javascript">
    window.onload = function () {
        var chart = new CanvasJS.Chart("chartContainer", {
            theme: "light2",
            backgroundColor: "transparent",
            animationEnabled: true,
            title: {
                fontColor: "#18bc9c",
                text: "OVERVIEW"
            },
            subtitles: [{
                text: "University rating by users",
                fontColor: "#18bc9c"
            }],
            axisX: {
                valueFormatString: "#",
                interval: 1
            },
            data: [{
                type: "column", // Change type to bar, line, area, pie, etc
                dataPoints: @Html.Raw(ViewBag.DataPoints)
            }]
        });

        chart.render();
    };
</script>

<div>
    <h3>Location</h3>
    <iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"
            src="@ViewBag.GoogleMapUri" style="border: 1px solid black"></iframe>
</div>

Webserver/Views/Universities/Edit.cshtml
@model Models.University

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<p>
    @Html.ActionLink("Back to Details", "Details", new { id = Model.Id })
</p>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Webserver/Views/Universities/Index.cshtml
@model Webserver.Models.ViewModels.Pagination.PagerViewModel<Models.University, Webserver.Enums.UniversitySortOrder>

@{
    ViewBag.Title = "Universities";
}

<h2>Search for universities: </h2>

@using (Html.BeginForm("Index", "Universities", new { page = Model.Pager.CurrentPage, sortOrder = Model.SortOrder }, FormMethod.Get))
{
    <span>@Html.TextBox("searchCriteria", Session["UniversitySearchCriteria"]?.ToString(), new { id = "txtbox" })</span>
    <span><input type="submit" value="Search" /></span>
    <span>@Html.DropDownList("country", new SelectList(Webserver.Helpers.CountryStore.CountryNames), "Select Country", new { id = "dropdwn" })</span>
}

<div class="tab-content">
    <table class="table">
        <tr>
            <th>
                @if (Model.SortOrder == Webserver.Enums.UniversitySortOrder.NAME_ASC)
                {
                    @Html.ActionLink("Name", "Index",
                        new { page = Model.Pager.CurrentPage, searchCriteria = ViewBag.SearchCriteria, sortOrder = Webserver.Enums.UniversitySortOrder.NAME_DESC, ViewBag.Country })
                }
                else
                {
                    @Html.ActionLink("Name", "Index",
                        new { page = Model.Pager.CurrentPage, searchCriteria = ViewBag.SearchCriteria, sortOrder = Webserver.Enums.UniversitySortOrder.NAME_ASC, ViewBag.Country })
                }
            </th>
            <th>
                @if (Model.SortOrder == Webserver.Enums.UniversitySortOrder.CITY_ASC)
                {
                    @Html.ActionLink("City", "Index",
                        new { page = Model.Pager.CurrentPage, searchCriteria = ViewBag.SearchCriteria, sortOrder = Webserver.Enums.UniversitySortOrder.CITY_DESC, ViewBag.Country })
                }
                else
                {
                    @Html.ActionLink("City", "Index",
                        new { page = Model.Pager.CurrentPage, searchCriteria = ViewBag.SearchCriteria, sortOrder = Webserver.Enums.UniversitySortOrder.CITY_ASC, ViewBag.Country })
                }
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Items.LastOrDefault().Description)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Items)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id })
                </td>
            </tr>
        }
    </table>
</div>

@if (Model.Pager.EndPage > 1)
{
    <ul class="pagination">
        @if (Model.Pager.CurrentPage > 1)
        {
            <li>
                @Html.ActionLink("First", "Index", new { searchCriteria = ViewBag.SearchCriteria, sortOrder = Model.SortOrder, ViewBag.Country })
            </li>
            <li>
                @Html.ActionLink("Previous", "Index", new { page = Model.Pager.CurrentPage - 1, searchCriteria = ViewBag.SearchCriteria, sortOrder = Model.SortOrder, ViewBag.Country })
            </li>
        }

        @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
        {
            <li class="@(page == Model.Pager.CurrentPage ? "active" : "")">
                @Html.ActionLink(page.ToString(), "Index", new { page = page, searchCriteria = ViewBag.SearchCriteria, sortOrder = Model.SortOrder, ViewBag.Country })
            </li>
        }

        @if (Model.Pager.CurrentPage < Model.Pager.TotalPageCount)
        {
            <li>
                @Html.ActionLink("Next", "Index", new { page = Model.Pager.CurrentPage + 1, searchCriteria = ViewBag.SearchCriteria, sortOrder = Model.SortOrder, ViewBag.Country })
            </li>
            <li>
                @Html.ActionLink("Last", "Index", new { page = Model.Pager.TotalPageCount, searchCriteria = ViewBag.SearchCriteria, sortOrder = Model.SortOrder, ViewBag.Country })
            </li>
        }
    </ul>
}

@if (Request.IsAuthenticated)
{
    if (User.IsInRole("Administrator"))
    {
        <p>
            @Html.ActionLink("Add", "Add")
        </p>
    }
}